### ISSUE TITLE
Gradle 6.0 support: DefaultTask.newInputDirectory() method has been deprecated

### ISSUE THREAD

**Issue by vlsi** [eskatos/creadur-rat-gradle#12]
The following line produces a warning:

https://github.com/eskatos/creadur-rat-gradle/blob/0ac6c21f166ca8f3a9e9ae5ab272d961eab53fe7/src/main/kotlin/org/nosphere/apache/rat/RatTask.kt#L63

Could the plugin update to newer API to silence warnings for current Gradle versions?

**Comment by eskatos** [comment]
Thanks for raising this @vlsi. I fixed this warning and the other two remaining ones while retaining backwards compatibility in 916c32f62ea2b39de50bdb74af31a7354f7c602c. This has been published as `0.5.1`.
