### ISSUE TITLE
Docs: Kotlin example for readme not correct

### ISSUE THREAD

**Issue by paul-bjorkstrand** [eskatos/creadur-rat-gradle#13]
In the readme
```
    // Input directory, defaults to '.'
    inputDir.set("some/path")
```
should be 
```
    // Input directory, defaults to '.'
    inputDir.set(file("some/path"))
```

**Comment by paul-bjorkstrand** [comment]
I can try to create a PR here this week, just buried, and wanted to document it.

**Comment by eskatos** [comment]
Thanks for the heads up @paul-bjorkstrand, fixed in https://github.com/eskatos/creadur-rat-gradle/commit/18b31359ff7220238c1908f11d69d4ef8a02f075
