### ISSUE TITLE
Support Gradle 6.0

### ISSUE THREAD

**Issue by vlsi** [eskatos/creadur-rat-gradle#14]
```
Could not create task ':rat'.
> Could not create task of type 'RatTask'.
   > org.nosphere.apache.rat.RatTask.newInputDirectory()Lorg/gradle/api/file/DirectoryProperty;
```

**Comment by eskatos** [comment]
Thanks for the report @vlsi.

What version of the plugin did you use?
What version of 6.0 did you use?

Plugin 0.4.0 works for me with 6.0-20190928230021+0000.

**Comment by vlsi** [comment]
I'm using 0.5.0: https://github.com/apache/jmeter/blob/e1794097b0255c6fe65c088834484e6c753d2aeb/build.gradle.kts#L36

It looks like I'm missing https://github.com/eskatos/creadur-rat-gradle/commit/916c32f62ea2b39de50bdb74af31a7354f7c602c

**Comment by eskatos** [comment]
Hum, sorry, I meant `0.5.2`, not `0.4.0`.

**Comment by vlsi** [comment]
0.5.2 indeed solves the issue, thanks
