### ISSUE TITLE
Can RAT plugin have text output? (for CI)

### ISSUE THREAD

**Issue by vlsi** [eskatos/creadur-rat-gradle#15]
It looks like the new RAT plugin always wants to print HTML output, and it is extremely complicated for CI servers like Travis.

Sample: https://travis-ci.org/vlsi/jmeter/jobs/592243274#L755

Is there a way to revert to text output?

I guess it would be nice if the plugin could detect CI env automatically (e.g. `CI=Y` environment variable) and adapt the output accordingly (e.g. print the brief summary on violations).

**Comment by vlsi** [comment]
For the reference, the violation is caused by `./gradlew wrapper` task that kills license header on top of `gradle/wrapper/gradle-wrapper.properties` file.

**Comment by eskatos** [comment]
Thanks for the report @vlsi 

If the rat task is configured to be verbose, then the plain text report is printed to the console.
Only a link to the HTML report is printed.

In the Travis output you linked I can only see the latter:

```
* What went wrong:
Execution failed for task ':rat'.
> A failure occurred while executing org.nosphere.apache.rat.RatWork
   > Apache Rat audit failure - 1 unapproved license
     	See file:///home/travis/build/vlsi/jmeter/build/reports/rat/index.html
```

There's a lot of XML output above that but it is unrelated and doesn't come from this plugin.

Could you please clarify your request?

As for the `wrapper` task removing comments from `gradle/wrapper/gradle-wrapper.properties`, please open an issue on `gradle/gradle`.

**Comment by eskatos** [comment]
Here's how you would enable the verbose mode on CI:

```kotlin
val isCI = System.getenv("CI") == "true" // ymmv
tasks.rat {
    verbose.set(isCI)
}
```
This will output the whole text report.

Maybe what you're after is a way to only print the "header" of that report to the console on any failure. That's something that could be considered.

**Comment by vlsi** [comment]
Oh. 
The question here is it would be nice to have a concise output (e.g. the list of the first 20 files with violations or something like that).

0.5.2

```
@@ -99,6 +99,7 @@

 val rat by tasks.getting(org.nosphere.apache.rat.RatTask::class) {
     gitignore(gitProps)
+    verbose.set(true)
     // Note: patterns are in non-standard syntax for RAT, so we use exclude(..) instead of excludeFile
     exclude(rootDir.resolve("rat-excludes.txt").readLines())
 }
```

```
$gw rat

> Task :rat FAILED
...
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':rat'.
> A failure occurred while executing org.nosphere.apache.rat.RatWork
   > Apache Rat audit failure - 154 unapproved licenses
        See file:///Users/vladimirsitnikov/Documents/code/jmeter/build/reports/rat/index.html

```

**Comment by vlsi** [comment]
It looks like the only thing verbose does it prints the full report to the console which is too much.

However, it does not seem to print the report: https://github.com/eskatos/creadur-rat-gradle/blob/master/src/main/kotlin/org/nosphere/apache/rat/RatWork.kt#L74-L81

Probably, `} else if (spec.verbose) {` should be replaced with `} if (spec.verbose) {`

**Comment by eskatos** [comment]
Good points, I'll see what I can do

**Comment by eskatos** [comment]
So, I reworked how the `verbose` flag works. It doesn't do anything when all files are valid. It prints the list of files with unapproved licences when some are found.

Implemented in https://github.com/eskatos/creadur-rat-gradle/commit/3157fcd92a0b778a54f7fd72d9c35d249ddcfffb

You can now use version `0.5.3` of the plugin

**Comment by vlsi** [comment]
Thanks for the fast fix (I've updated in https://github.com/apache/jmeter/commit/d33386e4ffcedb6818eb646944b5142bb701c50f ).
It would probably make sense to sort the list, but it does not matter that much.
