### ISSUE TITLE
Can Gradle Plugin support custom license matchers/families and approved licenses?

### ISSUE THREAD

**Issue by madrob** [eskatos/creadur-rat-gradle#16]
Hi, for Apache Lucene we are currently using the Ant RAT tasks and have a lot of customizations around it, but are looking at moving to Gradle and would like to use this plugin in that case.

We have a bunch of custom definitions for license matchers and feed them into a list of approved licenses using the expansions found here - https://creadur.apache.org/rat/apache-rat-tasks/types.html

The example code that we'd be migrating from can be found at https://github.com/apache/lucene-solr/blob/master/lucene/common-build.xml#L1886-L1950

I don't see a way to enable the lists of pattern matchers for approved licenses using this plugin - is this possible currently? Or if not, is it possible to add?

Thanks!

**Comment by eskatos** [comment]
Hi @madrob,
This is currently not possible but I had a look and it's quite simple to add.
Just opened https://github.com/eskatos/creadur-rat-gradle/pull/17 that should address your use case.
I'll publish a new release of the plugin soon.

**Comment by eskatos** [comment]
@madrob version `0.6.0` of the plugin is now available. See https://github.com/eskatos/creadur-rat-gradle#usage for how to use the new options.

**Comment by madrob** [comment]
Awesome, thanks! I'll take a look and come back with any questions should they arise!
