### ISSUE TITLE
Task `:rat` of type `org.nosphere.apache.rat.RatTask`: invocation of 'Task.project' at execution time is unsupported.

### ISSUE THREAD

**Issue by Goooler** [eskatos/creadur-rat-gradle#23]
- Repro: https://github.com/Goooler/jmh-gradle-plugin/pull/31
- Build scan: https://scans.gradle.com/s/ih2tiv2jja4z2/failure#1

**Comment by Goooler** [comment]
Seems the cause is

https://github.com/eskatos/creadur-rat-gradle/blob/6f4352d5a191378662390ff342860297194428e2/src/main/kotlin/org/nosphere/apache/rat/RatTask.kt#L138

and I send a minimum repro test case at https://github.com/Goooler/creadur-rat-gradle/pull/9.

**Comment by eskatos** [comment]
Thank you for the report and the regression test!

Fixed in https://github.com/eskatos/creadur-rat-gradle/commit/6b9c829874415fb0d4447f5eba6d6467c0fa1151

Available in version 0.8.1 of the plugin
