### ISSUE TITLE
The Project.getConvention() method has been deprecated.

### ISSUE THREAD

**Issue by Goooler** [eskatos/creadur-rat-gradle#24]
- See https://scans.gradle.com/s/xz4vhq3pyczgg/deprecations?expanded=WyIzIl0
- Seems it's related to https://github.com/eskatos/creadur-rat-gradle/blob/6f4352d5a191378662390ff342860297194428e2/src/main/kotlin/org/nosphere/apache/rat/RatTask.kt#L138
https://github.com/gradle/gradle/blob/bf8267c805558b1cbf29f0f39d94099a96f57e92/platforms/core-configuration/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/ProjectExtensions.kt#L138-L139

**Comment by eskatos** [comment]
Thank you for the report!

Fixed in https://github.com/eskatos/creadur-rat-gradle/commit/54d3dfe9822f0c010146a15f50ef0ef6f0281c53

Available in version 0.8.1 of the plugin
