### ISSUE TITLE
Build with JDK 5

### ISSUE THREAD

**Issue by eskatos** [eskatos/creadur-rat-gradle#4]
Nebula Test requires JDK>=7.
This issue is about removing this test dependency so the plugin can be built using JDK 5.

See https://issues.apache.org/jira/browse/RAT-163 and the associated dev@ discussion.

**Comment by jochenw** [comment]
Rather than fixing the Java version, lets move the Gradle Plugin out of the Rat Core build and to a separate subproject of Apache Creadur. That way, you can keep the JDK version at 7, and everyone should be happy.

**Comment by eskatos** [comment]
Then, someone from the Apache Creadur project should require a new repository from INFRA so we can push the code there. Any chances this would be a git repository? Otherwise, svn will do.

**Comment by jochenw** [comment]
A new subdirectory below creadur/ with trunk/branches/tags should be sufficient?

**Comment by eskatos** [comment]
Sure, anything that suits the Creadur people will do!
