### ISSUE TITLE
Is there a way to get the list of files that failed the license check to be output as part of the tasks failure output?

### ISSUE THREAD

**Issue by lukecwik** [eskatos/creadur-rat-gradle#8]
When running in a CI environment such as Jenkins, the output for failure requires access to the CI workspace (which may have been deleted) and the tasks failure is less then helpful since it prints something like:
```
Execution failed for task ':rat'.
> Found 5 files with unapproved/unknown licenses. See file:/home/jenkins/jenkins-slave/workspace/beam_PostCommit_Java_GradleBuild/src/build/reports/rat/rat-report.txt
```

It would be preferable to have the files listed in the failure output.

**Comment by lukecwik** [comment]
It turns out if you have plain output disabled, xml output enabled and verbose mode on you get a list of the failing licenses.

**Comment by lukecwik** [comment]
Note that the output would be improved if the failing licenses were available with plain output and as part of the summary exception when the task fails instead of logging as part of the command.

**Comment by eskatos** [comment]
Thanks for the report @lukecwik 
New version 0.4.0 should satisfy your needs. It embeds the plain report in the exception message, always.

**Comment by lukecwik** [comment]
Thanks, upgraded to the new version in https://github.com/apache/beam/pull/8240
