### ISSUE TITLE
Automatically exclude .gitignore paths

### ISSUE THREAD

**Issue by vlsi** [eskatos/creadur-rat-gradle#9]
What do you think if there was an option to apply `.gitignore` exclusions?

**Comment by vlsi** [comment]
@eskatos , what do you think if the task exposes `PatternFilterable` for the set of included/included files?
Or even `ConfigurableFileTree` instead of `inputDir` and `excludes`

I could then add `.gitignore` excludes via `org.gradle.api.tasks.util.PatternFilterable#exclude(org.gradle.api.specs.Spec<org.gradle.api.file.FileTreeElement>)`

**Comment by vlsi** [comment]
Just in case:
`ConfigurableFileTree`: https://github.com/eskatos/creadur-rat-gradle/pull/10
`PatternFilterable`: https://github.com/eskatos/creadur-rat-gradle/pull/11

Frankly speaking, I like `ConfigurableFileTree` better even though it kind of breaks backward compatibility.

Is there a chance you could review/merge/release it?

**Comment by vlsi** [comment]
@eskatos , sorry for pinging you directly, but could you clarify if you could look into #10 or #11?

If you won't be able to look into that, then could you please respond with a short notice?
Then I would probably fork the plugin and/or write my own.

**Comment by eskatos** [comment]
> What do you think if there was an option to apply .gitignore exclusions?

Would be nice indeed. Couldn't this be added upstream in rat instead?

BTW, sorry for the delay, I commented on both of your PRs.

**Comment by vlsi** [comment]
Thanks.

Finally Apache JMeter is migrated to Gradle, and new Rat API is used to exclude gitignore patterns: https://github.com/apache/jmeter/blob/7556991464f6e5aa214889fbf22be00e8d929083/build.gradle.kts#L99-L103
